type Theme = {
  night: string;
  sun: string;
};

export const day: Theme = {
  night: "bg-[url('/night.jpg')]",
  sun: "bg-[url('/9848253.jpg')]",
};

export const text = {
  title: "Date Night App",
  description:
    "Date Night is a fun and engaging app designed to bring couples closer and add excitement to their evenings. Discover new things about each other and enjoy memorable moments together.",
  features:
    "The app includes Truth or Dare challenges and intriguing questions across various topics, helping you uncover what your partner truly enjoys.",
  modes:
    "Date Night offers tailored game modes for every relationship style—whether you're together in person, in a long-distance relationship, or haven't met face-to-face yet.",
};

export const hotQuetions = [
  "What’s your biggest turn-on that you haven’t shared with me yet?",
  "If we could have a wild night anywhere in the world, where would it be?",
  "What’s the craziest thing you’ve ever fantasized about?",
  "What’s the most adventurous thing you want us to try in bed?",
  "Have you ever thought about someone else during our intimate moments?",
  "What’s your favorite part of my body?",
  "What’s the most unexpected place you’d like to get frisky?",
  "What’s the wildest place we’ve done it (or would do it)?",
  "What’s the naughtiest thing you’ve ever done with someone?",
  "What do you like more—slow and sensual or fast and intense?",
  "Do you like it when I take control, or do you prefer to be in charge?",
  "What’s something you’ve always wanted to try but never had the chance to?",
  "What type of lingerie would you like to see me in?",
  "Would you ever consider having a threesome or an open relationship?",
  "What’s something I do that drives you wild?",
  "What’s the best kiss you’ve ever had (from me or anyone)?",
  "Do you like it when I whisper in your ear during intimacy?",
  "What’s your guilty pleasure in bed?",
  "If we could role-play, what character would you like me to play?",
  "What’s the sexiest thing you’ve ever seen me do?",
  "What’s your favorite memory of us being intimate together?",
  "Would you prefer me to be a little more dominant, or do you prefer a more passive approach?",
  "Have you ever imagined us in a public setting, getting frisky?",
  "If I could read your mind during our intimate moments, what would I learn?",
  "What do you think about dirty talk? Do you want more of it?",
  "Would you ever let me surprise you with a date night or intimate experience?",
  "What’s something you haven’t told me yet about your fantasies?",
  "What’s the best thing about our chemistry in bed?",
  "If we had a weekend getaway to a private cabin, how would we spend it?",
  "Have you ever had a dream about me that turned you on?",
  "What’s the sexiest compliment I could give you during sex?",
  "Do you like it when I take my time with you, or do you prefer quick passion?",
  "What’s your favorite way for me to touch you?",
  "What’s something you’d never tell anyone but would tell me?",
  "If I could give you a sensual massage, where would you want me to focus?",
  "Would you ever share intimate details about our relationship with friends?",
  "If I kissed you in public, how would you feel about it?",
  "What’s one thing that instantly makes you feel more attracted to me?",
  "Have you ever watched porn with me? If not, would you want to?",
  "Would you ever consider sending me sexy texts or photos?",
  "What’s your favorite thing to do to turn me on?",
  "What’s the most romantic thing you’ve ever wanted to do for me?",
  "If I was to serenade you, how would you like it to go down?",
  "Do you like it when I take control in the bedroom or when I let you lead?",
  "Have you ever had a secret crush on someone else while we’ve been together?",
  "What’s something spontaneous you’d like us to do next time we’re alone?",
  "If I made a move on you in the middle of the day, how would you react?",
  "Would you ever consider doing something a little naughty in public for me?",
  "Do you prefer me to kiss you passionately or tease you before kissing?",
  "What’s your favorite type of foreplay with me?",
  "What do you think would make us hotter in the bedroom?",
  "What’s one thing you’ve always wanted to do but never dared to ask me?",
  "How do you feel about the idea of doing something taboo together?",
  "If I gave you a massage, where would you want me to focus?",
  "What’s your opinion on giving and receiving compliments in bed?",
  "Do you prefer intimacy with a lot of talking or silence?",
  "What would be the perfect surprise for you in a romantic setting?",
  "Have you ever wanted me to be more aggressive or more tender in bed?",
  "What’s something you’ve seen in a movie that you’d love for us to try?",
  "What’s your opinion on public affection, and how would you feel about it?",
  "If you had the opportunity to plan a night of passion, what would it look like?",
  "What kind of romantic gesture would make you feel most loved?",
  "What’s your favorite way to wake up next to me?",
  "Would you like me to be more spontaneous or plan things out in advance?",
  "What’s the sexiest thing I could say to you right now?",
  "What do you think makes our relationship unique in bed?",
  "Would you want to be blindfolded or restrained during our intimate time?",
  "If I was a stranger at a bar, how would you want me to approach you?",
  "What do you think about me taking control in the bedroom?",
  "Would you ever want us to explore other fantasies outside the bedroom?",
  "What’s something I could do to make our sex life more exciting?",
  "What do you think makes me irresistible to you?",
  "What would you do if I kissed you passionately in public?",
  "Do you think you could handle a weekend with no clothes?",
  "What’s your favorite way to let me know you want me?",
  "How do you feel about taking our intimate moments to the next level?",
  "What’s something you think would make us even closer in the bedroom?",
  "Would you ever want to try a new position or role in bed?",
  "If we could go on a spontaneous adventure, where would it be?",
  "What’s one intimate thing I could do to make you feel cherished?",
  "What’s the most exciting thing you’d like to try with me?",
  "How do you feel about dirty dancing or more sensual moves?",
  "Would you like to be in a relationship where we explore things more openly?",
  "What’s the most intimate gift you’ve ever received or would love to?",
  "How do you feel about the idea of having a ‘sexy’ bucket list?",
  "What would be the perfect scenario to fulfill a hidden fantasy of yours?",
  "What’s your opinion on experimenting with different power dynamics in bed?",
  "What’s the most thrilling thing you’d like us to do together?",
  "How would you feel if we had a weekend of complete intimacy and relaxation?",
  "What do you think would make our sex life even hotter?",
  "Would you like to take our fantasies and make them a reality?",
  "What would be your ideal romantic date to make you feel loved and sexy?",
  "Would you want to try something new and risky together?",
  "How do you feel about secret sexy texts or calls when we're apart?",
  "What’s something we could do to spice things up and keep it exciting?",
  "What’s one thing that really turns you on during intimacy?",
  "How do you feel about dressing up in costumes for fun?",
  "Would you be interested in exploring an entirely different kind of intimacy?",
];

export const distanceQuetions = [
  "What’s something you’ve fantasized about that you haven’t told me yet?",
  "What part of my body do you miss the most when we’re apart?",
  "Have you ever kissed someone and thought about me during it?",
  "What’s the naughtiest thing you’ve done when no one was around?",
  "Do you like it when I talk dirty to you over the phone?",
  "What’s the most adventurous place you’d want us to get frisky?",
  "What would you do if I showed up at your door unannounced in something sexy?",
  "What’s the sexiest thing I could say to you right now?",
  "Would you prefer me to send you a naughty pic, or would you rather have me describe something sexy?",
  "What’s your favorite way to tease me when we’re apart?",
  "If I were there right now, what would you want me to do first?",
  "What would you do if I kissed you passionately while we were out in public?",
  "How would you feel if I sent you a surprise naughty video?",
  "Would you want to role-play over the phone or video chat sometime?",
  "If we could be together right now, what’s the first thing you would want to do?",
  "What’s the most daring thing you would want to try together in person?",
  "What would be your dream romantic night over video call?",
  "How do you feel about me sending you a sexy text when we're apart?",
  "If I gave you a challenge, would you do it over the phone or video call?",
  "What’s the most seductive thing I could do for you from a distance?",
  "What’s something I could do to make you feel extra desired when we’re apart?",
  "What’s one of your secret fantasies that you want to share with me?",
  "If you could imagine our next meeting, what would be your ultimate fantasy?",
  "Would you want me to surprise you with a sexy gift through the mail?",
  "What do you miss most about being physically close to me?",
  "How would you feel if I sent you a pic in my favorite outfit just for you?",
  "Would you want me to send you a naughty voice message?",
  "What’s the craziest thing you’ve wanted to try with me in bed?",
  "How would you react if I whispered a naughty suggestion into your ear?",
  "What’s your idea of a perfect video date night?",
  "Do you like it when I tell you what I’d do to you if I were there?",
  "What’s the most intimate thing you want us to do over a video call?",
  "Would you ever consider sending me a sexy photo of yourself?",
  "If I were there right now, how would you want me to wake you up?",
  "Would you like to send me a spicy text challenge?",
  "What’s the hottest thing you’ve done in our long-distance relationship?",
  "How would you react if I showed up in a surprise outfit when we meet again?",
  "What’s your favorite part of me to fantasize about?",
  "Do you enjoy it when I tell you how much I miss you during intimate moments?",
  "What’s your idea of a perfect long-distance love moment?",
  "Send me a selfie in your favorite outfit.",
  "Do a sexy dance on video for me.",
  "Send me a text describing what you're wearing right now.",
  "Let me pick out your next outfit for our video date.",
  "Tell me something naughty you’ve always wanted to do, but haven’t yet.",
  "Record a voice message describing how much you miss me.",
  "Send me a video of you doing something you know I’d find sexy.",
  "Do something spontaneous and text me a picture of it.",
  "Tell me what you're wearing, and make it a little bit spicy.",
  "Make a video showing me how you would kiss me if I were there.",
  "Send me a voice note with a sexy secret you’ve never told me.",
  "Tell me about a fantasy you haven’t shared yet and make it as detailed as possible.",
  "Send me a video of you slowly taking off a piece of clothing.",
  "Text me one of your most daring fantasies, but don’t hold back.",
  "Give me a dare, and I’ll do it for you on the next video call.",
  "Send me a picture of you doing something sexy but creative.",
  "Tell me what you wish you could do with me right now, in the most vivid detail.",
  "Make a video of you doing a sensual movement, like a slow dance.",
  "Send me a naughty text that I would never expect from you.",
  "Do a surprise challenge for me and send me a video of the result.",
  "Give me a kiss through the camera, and make it as real as possible.",
  "Make a list of three things you would want us to do next time we’re together.",
  "Describe how you’d seduce me if I were there right now.",
  "Record yourself saying something sexy in your voice, just for me.",
  "Send me a message that describes a fantasy I could fulfill when we’re together.",
  "Record a sexy video of yourself and send it as a surprise.",
  "Text me a daring truth or dare challenge, and I’ll reply with mine.",
  "Take a seductive selfie and send it with no explanation.",
  "Make a video of you trying on a new outfit and give me a mini runway show.",
  "Do something spontaneous and send me a picture of it.",
  "Let me pick a song, and then record yourself dancing to it for me.",
  "Tell me about the sexiest dream you’ve ever had involving us.",
  "Challenge me to do something sexy, and I’ll do it for you.",
  "Send me a video of you trying something playful with your clothes, like unbuttoning your shirt.",
  "Record a voice note of you saying something naughty just for me.",
  "Describe to me the feeling of being kissed by me, but in extreme detail.",
  "What’s the most romantic thing you could do for me over a video call?",
  "If I were there right now, how would you want to start our day?",
  "What would be the most daring thing you’d do to make me feel special?",
  "How would you react if I sent you a naughty surprise?",
  "If you could plan the most romantic evening over video chat, what would it look like?",
  "Would you ever let me choose your next outfit for our video date?",
  "How do you want to make our next reunion unforgettable?",
  "What’s the most fun thing we could do over a video call to keep things spicy?",
  "If I were there, what’s the first thing you’d want to do to surprise me?",
  "What’s the most intimate thing you’d want to do on a video call?",
  "How do you feel about sending me a surprise sexy package?",
  "What would you do if I showed up at your door unexpectedly?",
  "Would you ever be open to video calling in the shower for me?",
  "What’s the one thing you want to do when we’re finally together again?",
  "How do you feel about doing something naughty in public next time we’re together?",
  "Would you ever want to try a sexy game over a video call?",
  "What’s the craziest thing you’d want us to do when we’re in the same place again?",
  "If I could give you one surprise, what would it be?",
  "Would you ever consider me sending you something intimate and private through the mail?",
];
